# Generated by Django 3.2.7 on 2021-10-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_type_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location_id',
            field=models.IntegerField(null=True),
        ),
    ]
