# Generated by Django 3.2.7 on 2021-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211020_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_entry',
            name='shift_length',
            field=models.FloatField(),
        ),
    ]
