# Generated by Django 3.2.7 on 2021-10-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_timesheet_entry_shift_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
