# Generated by Django 3.2.7 on 2021-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accum_hrs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='total_hrs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
