# Generated by Django 3.2.7 on 2021-11-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211104_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Settings',
            fields=[
                ('setting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
    ]
